### ISSUE TITLE
radsecproxy not work with freeradius

### ISSUE THREAD

**Issue by ricardobarbosams** [radsecproxy/radsecproxy#99]
Hello, all

I'm trying setting the environment with freeradius e radsecproxy, but not work. My environment.

- 192.168.11.43 - freeradius
- 192.168.11.96 - radsec
- 192.168.10.2 - client

I'm using the jradius client for test.  Using the radtest command  from radsecproxy works, but client doesn't.

The radsecproxy configuration

```
ListenUDP               *:1812
ListenUDP               *:1813
LogLevel                3
LogDestination  file:///var/log/radsecproxy.log
LoopPrevention on
tls default {
	CACertificateFile /certs/certificate.crt
	CertificateFile /certs/certificate.crt
	CertificateKeyFile /certs/certificate.key
	CertificateKeyPassword "123456"
}
client ricardo {
	host 192.168.10.2
	type tls
	certificatenamecheck off
	secret testing123
}
server freeradius_auth {
	host 192.168.11.43:1812
	type udp
	StatusServer on
	secret testing123
}
server freeradius_acct {
	host 192.168.11.43:1813
	type udp
	StatusServer on
	secret testing123
}
realm * {
	server freeradius_auth
	accountingserver freeradius_acct
}
```

radsecproxy logs:

```
# radsecproxy -f -d 5 -c /etc/radsecproxy.conf
reading config from /etc/radsecproxy.conf
reading config file /etc/radsecproxy.conf
getgenericconfig: ListenUDP = *:1812
getgenericconfig: ListenUDP = *:1813
getgenericconfig: LogLevel = 3
getgenericconfig: LogDestination = file:///var/log/radsecproxy.log
getgenericconfig: LoopPrevention = on
conftls_cb called for tls default
getgenericconfig: block tls default: CACertificateFile = /certs/certificate.crt
getgenericconfig: block tls default: CertificateFile = /certs/certificate.crt
getgenericconfig: block tls default: CertificateKeyFile = /certs/certificate.key
getgenericconfig: block tls default: CertificateKeyPassword = 123456
tlsaddcacrl: updated TLS context default
tlscreatectx: created TLS context default
conftls_cb: added TLS block default
confclient_cb called for client ricardo
getgenericconfig: block client ricardo: host = 192.168.10.2
getgenericconfig: block client ricardo: type = tls
getgenericconfig: block client ricardo: certificatenamecheck = off
getgenericconfig: block client ricardo: secret = testing123
resolvehostport: 192.168.10.2 -> 192.168.10.2
confserver_cb called for server freeradius_auth
getgenericconfig: block server freeradius_auth: host = 192.168.11.43:1812
getgenericconfig: block server freeradius_auth: type = udp
getgenericconfig: block server freeradius_auth: StatusServer = on
getgenericconfig: block server freeradius_auth: secret = testing123
resolvehostport: 192.168.11.43 -> 192.168.11.43
confserver_cb called for server freeradius_acct
getgenericconfig: block server freeradius_acct: host = 192.168.11.43:1813
getgenericconfig: block server freeradius_acct: type = udp
getgenericconfig: block server freeradius_acct: StatusServer = on
getgenericconfig: block server freeradius_acct: secret = testing123
resolvehostport: 192.168.11.43 -> 192.168.11.43
confrealm_cb called for realm *
getgenericconfig: block realm *: server = freeradius_auth
getgenericconfig: block realm *: accountingserver = freeradius_acct
addrealm: constructed regexp .* from *
addsrvconfs: added server freeradius_auth for realm *
addsrvconfs: added server freeradius_acct for realm *
addrealm: added realm *
closing config file /etc/radsecproxy.conf
Tue Jan 11 12:12:00 2022: radsecproxy 1.9.1 starting
Tue Jan 11 12:12:00 2022: resolvehostport: (src info not available) -> 0.0.0.0
Tue Jan 11 12:12:00 2022: disable_DF_bit: disabling DF bit (Linux variant)
Tue Jan 11 12:12:00 2022: addserverextraudp: creating new socket #3 (0.0.0.0) for server freeradius_auth
Tue Jan 11 12:12:00 2022: addserverextraudp: reusing existing socket #3 (0.0.0.0) for server freeradius_acct
Tue Jan 11 12:12:00 2022: initextraudp: spinning up clientrd thread for socket #3
Tue Jan 11 12:12:00 2022: resolvehostport: (src info not available) -> 0.0.0.0
Tue Jan 11 12:12:00 2022: createlistener: listening for tls on *:2083
Tue Jan 11 12:12:04 2022: tlsservernew: incoming TLS connection from 192.168.10.2
Tue Jan 11 12:12:04 2022: tlsservernew: SSL_accept failed
```

jradius logs

```
KeyStore Alias: 1
net.jradius.exception.TimeoutException: Timeout: No Response from RADIUS Server
	at net.jradius.client.RadiusClientTransport.sendReceive(RadiusClientTransport.java:115)
	at net.jradius.radsec.RadSecClientTransport.sendReceive(RadSecClientTransport.java:103)
	at net.jradius.client.RadiusClient.authenticate(RadiusClient.java:344)
	at net.jradius.client.gui.JRadiusSimulator$SimulationRunner.run(JRadiusSimulator.java:2678)
	at java.base/java.lang.Thread.run(Thread.java:829)
Sent: 1 Recd: 0 in 92ms
net.jradius.client.gui.JRadiusSimulator$SimulationRunner@2ba1d677
```

jradius configuration.

![image](https://user-images.githubusercontent.com/53918764/148941254-7eaa9cd2-48b4-49d3-8fb2-1d90faab954e.png)
![image](https://user-images.githubusercontent.com/53918764/148941280-32a47acb-21ef-4b9b-be23-f9599ff842e6.png)
![image](https://user-images.githubusercontent.com/53918764/148941305-152fbad4-e3a6-41a6-826d-6bd721f6f159.png)
![image](https://user-images.githubusercontent.com/53918764/148941464-9d210b8d-fc32-4719-8e72-0b82b57ac1a5.png)

The certificate is generate with command.

```bash
# openssl req -x509 -sha256 -newkey rsa:2048 -keyout certificate.key -out certificate.crt -days 1024 -nodes
# openssl pkcs12 -inkey certificate.key -in certificate.crt -export -out certificate.p12
# keytool -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore certificate.jks -deststoretype JKS
# ls -1
certificate.crt
certificate.jks
certificate.key
certificate.p12
```

Let me known what i'm doing wrong

**Comment by rodrigoSyscop** [comment]
Próximo passo:

tentar usar um certificado válido do LetsEncrypt.

**Comment by fmauchle** [comment]
Apologies for the late reply.

The TLS handshake seems to fail at a very early stage. Please use logLevel 5 to see the full debug log.

Another small thing: you are creating the key without a password (`-nodes`) but still specifying a key password on both ends. Not sure if this causes any issues (it likely doesn't), but maybe something to check.

**Comment by hgot07** [comment]
Have you tried FreeRADIUS 3.2?

**Comment by alandekok** [comment]
I would also suggest using FreeRADIUS 3.2.3, which has had some fixes in the TLS handling code.

And if that doesn't work, please also post the debug output from FreeRADIUS.

**Comment by omnine** [comment]
Hi @ricardobarbosams , I may have solved your puzzle.

I tried your scenario myself, and got the same error. Then I checked JRADIUS source code, unfortunately that project is inactive, I found it missed one line `socket.startHandshake();`. No wonder I could not see any handshake traffic with Wireshark.

You can try my build at https://github.com/omnine/jradius/releases/tag/1.1.6.3

Please also check #154  if you are going to use the latest code of `radsecproxy`. It took me days to work it out. Thanks the java SSL debug parameter, `-Djavax.net.debug=ssl:handshake`, it gave me this  message,

`No X.509 certificate for client authentication, use empty Certificate message instead`

Luckily in Wireshark I noticed the wrong DN which filtered out the client certificate I provided. 

In a summary, you need to update both JRADIUS and radsecproxy.
